dbfolder = 'path to FLO Token Scanner data folder'
sse_pubKey = ''
apiUrl = 'flosight api url'
apilayerAccesskey = 'api layer access key'
FLO_DATA_DIR = '/home/username/.flo'
FLO_CLI_PATH = '/usr/local/bin/flo-cli'
